# fly.toml app configuration file generated for sol-vanity-silent-voice-2821 on 2025-02-19T22:07:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sol-vanity-silent-voice-2821'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  gpus = 1
  gpu_kind = 'a100-sxm4-80gb'
